import * as THREE from './vendor/three.module.js';

export function createAdventure({scene,camera,person,scholar,state,mat,mesh,box,cylinder,beam,toast,tone,chime,thunder,onComplete,onChanged}){
  const $=id=>document.getElementById(id),stations=[],pickables=[],labels=[],pipes=[];
  const cream=mat('paleStone','#ede4c9'),wood=mat('wood','#b68a55'),ink=mat('darkWood','#4f524b'),stone=mat('stone','#93a4a3'),red=mat('red','#bd533f'),brass=mat('adventure-brass','#c09b58');
  const water=new THREE.MeshToonMaterial({color:'#5abfba',transparent:true,opacity:.9}),spark=new THREE.MeshBasicMaterial({color:'#f4ca76',transparent:true,opacity:.9});
  const quest={pipes:[1,3,1],peg:false,repaired:false,rhythm:[],stable:0,pressure:20,completed:[],events:[]};
  let travel=null,collision=null,selected=null,nearest=null,held=null,drumBounce=0,lastUI='',clock=0,occluders=[];
  function group(x,y,z){const g=new THREE.Group();g.position.set(x,y,z);scene.add(g);return g;}
  function register(id,name,g,point,preferred,range=1.25){const s={id,name,group:g,point:new THREE.Vector3(...point),preferred,range};stations.push(s);g.traverse(o=>{if(o.isMesh){o.userData.stationId=id;pickables.push(o);}});return s;}
  function label(s,text){const b=document.createElement('button');b.className='scene-tag adventure-tag';b.dataset.station=s.id;b.textContent=s.id.startsWith('pipe')?['一','二','三'][Number(s.id.at(-1))]:text;b.setAttribute('aria-label','走近'+s.name);b.onclick=()=>select(s.id);$('adventure-tags').append(b);labels.push({s,b});}
  // Three rotating troughs really join: water only enters connected segments.
  for(let i=0;i<3;i++){const x=-3.85+i*.72,z=4.5,g=group(x,.24,z);cylinder(.34,.36,.26,stone,0,.14,0,g,24);cylinder(.31,.31,.035,brass,0,.29,0,g,32);const rotor=new THREE.Group();rotor.position.y=.35;g.add(rotor);box(.64,.06,.23,wood,0,0,0,rotor);for(const side of [-1,1])box(.66,.13,.035,wood,0,.055,side*.12,rotor);const fill=box(.65,.012,.18,water,0,.04,0,rotor);fill.visible=false;const arrow=mesh(new THREE.ConeGeometry(.057,.12,3),cream,.16,.09,0,rotor);arrow.rotation.z=-Math.PI/2;rotor.rotation.y=quest.pipes[i]*Math.PI/2;pipes.push({g,rotor,fill,target:rotor.rotation.y});const s=register('pipe'+i,'第'+(i+1)+'段水槽',g,[x,.78,z],[[x,5.15],[x,3.83]],1.05);label(s,['壹 ↻','贰 ↻','叁 ↻'][i]);}
  const source=group(-4.34,.24,4.5);cylinder(.14,.18,.3,stone,0,.15,0,source);const spout=box(.32,.07,.12,wood,.06,.36,0,source);const feed=box(.33,.012,.09,water,.07,.405,0,source);
  // Wooden locking peg waits on the existing tea bench, not in an inventory menu.
  const peg=group(-3.9,.8,7);const pin=cylinder(.038,.048,.35,wood,0,0,0,peg,10);pin.rotation.z=Math.PI/2;box(.07,.14,.1,brass,.15,0,0,peg);const pegRing=mesh(new THREE.TorusGeometry(.20,.012,6,40),spark,0,.22,0,peg);pegRing.rotation.x=Math.PI/2;
  const pegStation=register('peg','茶凳上的木销',peg,[-3.9,.83,7],[[-4.65,6.45],[-3.9,6.35],[-3.15,7.2]],1.5);label(pegStation,'木销');
  // An on-shore axle bearing is visibly connected to the old water wheel.
  const bearing=group(3.45,.24,1.67);box(.46,.19,.4,stone,0,.095,0,bearing);box(.34,.38,.24,wood,0,.36,0,bearing);const socket=mesh(new THREE.TorusGeometry(.082,.016,8,24),ink,0,.39,.132,bearing);const fixedPeg=cylinder(.034,.043,.25,brass,0,.39,.18,bearing,12);fixedPeg.rotation.x=Math.PI/2;fixedPeg.visible=false;beam([3.45,.67,1.6],[3.45,.92,.3],.035,ink);
  const repairStation=register('repair','水车轴座',bearing,[3.45,.88,1.67],[[3.05,2.2],[2.75,1.8],[3.45,2.4]],1.35);label(repairStation,'修水车');
  // The drum carries a bottom-to-top long/short/short instruction, an original rhythm mechanic.
  const drum=group(1.3,.24,4.45);for(const s of [-1,1]){box(.07,.56,.07,wood,s*.22,.28,0,drum);beam([s*.22,0,-.22],[s*.22,.42,0],.033,wood,drum);}const barrel=cylinder(.255,.255,.25,red,0,.59,0,drum,32);barrel.rotation.x=Math.PI/2;
  for(const z of [-.135,.135]){const face=cylinder(.246,.246,.014,cream,0,.59,z,drum,32);face.rotation.x=Math.PI/2;const rim=mesh(new THREE.TorusGeometry(.253,.017,8,40),brass,0,.59,z,drum);}
  const drumSkin=mesh(new THREE.CircleGeometry(.22,32),cream,0,.59,.15,drum);const beatLights=[];for(let i=0;i<3;i++){const m=spark.clone();m.color.set('#a5b7a5');const dot=mesh(new THREE.SphereGeometry(.035,10,8),m,(i-1)*.14,.97,0,drum);beatLights.push(dot);}
  const plaque=group(1.8,.24,4.4);box(.18,.8,.08,wood,0,.4,0,plaque);for(let i=0;i<3;i++){const y=.3+i*.16;if(i===0)box(.14,.036,.022,cream,0,y,.055,plaque);else for(const s of [-1,1])box(.055,.036,.022,cream,s*.045,y,.055,plaque);}
  const drumStation=register('drum','雷纹鼓',drum,[1.3,1.25,4.45],[[1.3,5.2],[.6,4.5],[1.1,3.7]],1.18);label(drumStation,'雷纹鼓');
  const valve=group(2.68,.24,6.9);box(.35,.15,.36,stone,0,.075,0,valve);cylinder(.065,.09,.65,wood,0,.42,0,valve,12);const handwheel=new THREE.Group();handwheel.position.set(0,.77,.02);valve.add(handwheel);mesh(new THREE.TorusGeometry(.24,.032,10,36),brass,0,0,0,handwheel);for(let i=0;i<4;i++){const a=i*Math.PI/2;beam([0,0,0],[Math.cos(a)*.23,Math.sin(a)*.23,0],.018,wood,handwheel);}cylinder(.045,.045,.08,ink,0,.77,0,valve);
  const gauge=group(3.06,.24,6.86);box(.19,1.08,.16,stone,0,.54,0,gauge);const gaugeWater=box(.1,.01,.025,water,0,.13,.095,gauge);for(let i=0;i<=5;i++)box(.15,.014,.025,i===3?red:cream,0,.16+i*.16,.103,gauge);const gaugeMark=box(.23,.025,.04,red,0,.64,.105,gauge);
  const valveStation=register('valve','荷塘水闸',valve,[2.68,1.2,6.9],[[2.0,6.85],[2.65,6.15],[2.1,7.55]],1.2);label(valveStation,'调水闸');
  const gateAnchor=new THREE.Group();gateAnchor.position.set(0,0,-3.85);scene.add(gateAnchor);const gateStation=register('gate','山门',gateAnchor,[0,2.6,-3.28],[[0,-3.85]],1.3);label(gateStation,'走过山门');
  const selection=mesh(new THREE.RingGeometry(.39,.415,48),new THREE.MeshBasicMaterial({color:'#dcab62',transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}),0,.3,0);selection.rotation.x=-Math.PI/2;selection.visible=false;
  const ray=new THREE.Raycaster();
  function visibleTo(s,x=person.position.x,z=person.position.z){if(!collision)return false;const start=new THREE.Vector3(x,collision.heightAt(x,z)+.53,z),d=s.point.clone().sub(start),len=d.length();ray.set(start,d.normalize());ray.far=Math.max(.01,len-.09);return !ray.intersectObjects(occluders,false).some(h=>h.object.userData.stationId!==s.id);}
  function near(s){return Math.hypot(person.position.x-s.point.x,person.position.z-s.point.z)<=s.range&&visibleTo(s);}
  function available(s){return !(s.id==='peg'&&quest.peg)&&!(s.id==='gate'&&state.phase<3);}
  function approach(s){const candidates=[...s.preferred];for(const radius of [.8,1.05])for(let i=0;i<12;i++)candidates.push([s.point.x+Math.cos(i*Math.PI/6)*radius,s.point.z+Math.sin(i*Math.PI/6)*radius]);candidates.sort((a,b)=>Math.hypot(person.position.x-a[0],person.position.z-a[1])-Math.hypot(person.position.x-b[0],person.position.z-b[1]));for(const [x,z] of candidates){if(Math.hypot(x-s.point.x,z-s.point.z)>s.range||!collision.canWalk(x,z)||!visibleTo(s,x,z))continue;if(travel.route(x,z))return [x,z];}return null;}
  function blocked(){return !!document.querySelector('dialog[open]')||document.hidden;}
  function event(id,detail){quest.events.push({id,detail,time:performance.now(),position:person.position.toArray()});state.attempts++;scholar.interact();travel.face?.(stations.find(s=>s.id===id)?.point);}
  function act(id,{duration=0,delta=1}={}){
    const s=stations.find(s=>s.id===id);if(!s||blocked()||!available(s))return false;if(!near(s)){toast('要走到'+s.name+'旁边才能操作。');return false;}travel.cancel();selected=s;event(id,{duration,delta});
    if(id.startsWith('pipe')){if(state.phase>0){toast('水槽已经扣紧，清流正在入渠。');return false;}const i=Number(id.at(-1));quest.pipes[i]=(quest.pipes[i]+1)%4;pipes[i].target+=Math.PI/2;tone(240+i*70,.13);toast('旋转第'+(i+1)+'段水槽 · 让槽口连成横渠');}
    else if(id==='peg'){quest.peg=true;peg.visible=false;chime();toast('收起木销。去河边，将它装回水车轴座。');}
    else if(id==='repair'){if(state.phase<1){toast('水渠还没接通。先转动竹径旁的三段水槽。');return false;}if(!quest.peg){toast('轴座缺了一枚木销。到竹径尽头的茶凳找一找。');return false;}if(quest.repaired){toast('轴座修好了。去敲雷纹鼓，唤醒水车。');return false;}quest.repaired=true;fixedPeg.visible=true;chime();toast('木销已归位 · 水轮可以转动了，还需要一次雷鼓启动。');}
    else if(id==='drum'){if(!quest.repaired){toast('轴座还没有修好，雷鼓暂时带不动水车。');return false;}if(state.phase>=2){toast('雷纹已回应，去荷塘边调节水闸。');return false;}const beat=duration>=.42?'long':'short',expected=['long','short','short'];drumBounce=1;tone(beat==='long'?105:240,beat==='long'?.5:.16,.12);if(beat!==expected[quest.rhythm.length]){quest.rhythm=[];toast('节奏不对。读鼓旁爻牌，自下向上：长、短、短。');}else{quest.rhythm.push(beat);toast(quest.rhythm.length===3?'雷纹回应 · 水车开始转动':'已敲 '+quest.rhythm.length+' / 3 · '+(quest.rhythm.length===1?'接下来短按两次':'再短按一次'));if(quest.rhythm.length===3){state.phase=2;state.upper=[0,0,1];thunder();$('weather').textContent='雷雨将歇';}}}
    else if(id==='valve'){if(state.phase<2){toast('水车尚未启动，先修好轴座并敲响雷鼓。');return false;}if(state.phase>=3){toast('桥闩已经扣稳，去走完归路。');return false;}state.flow=THREE.MathUtils.clamp(state.flow+delta*10,0,100);tone(180+state.flow*3,.09);toast('水闸 '+state.flow+'% · 将水位稳在朱线附近');}
    else if(id==='gate'){if(state.phase===3)toast('沿石阶穿过山门，归路就在前方。');}
    onChanged();refreshUI();return true;
  }
  function select(id,options={}){const s=stations.find(s=>s.id===id);if(!s||!available(s)||blocked())return false;selected=s;if(id==='gate'){if(state.bridge<=.985){toast('木桥还在落下，稍等片刻再走。');return false;}return travel.command(0,-3.9);}if(near(s))return act(id,options);const p=approach(s);if(!p){toast('这条路暂时走不过去，换个方向靠近。');return false;}travel.command(...p);toast('走近'+s.name+' · 到旁边后按 E 或再点一次操作');return true;}
  function description(s){if(!s)return ['在庭院里寻找机关','WASD 行走 · 点机关走近'];if(s.id.startsWith('pipe'))return state.phase>0?['水槽已接通','沿竹径去找木销，再到河边修水车']:['旋转'+s.name,'E / 点击旋转 90° · 三段槽口连成横渠'];if(s.id==='peg')return ['拾取木销','E / 点击拾取 · 带回河边轴座'];if(s.id==='repair')return [quest.repaired?'轴座已修复':'修复水车轴座',quest.repaired?'去雷纹鼓旁，长按一次再短按两次':quest.peg?'E / 点击安装木销':'缺少木销 · 去竹径尽头的茶凳寻找'];if(s.id==='drum')return state.phase>=2?['雷纹已回应','去荷塘边调节水闸']:['敲响雷纹鼓','按住 E 或操作键 0.5 秒再松开，接着短按两次'];if(s.id==='valve')return state.phase>=3?['桥闩已扣稳','沿木桥走过山门，归路就在前方']:['调节水闸 · '+state.flow+'%','E 开大 / Q 关小 · 水位停在朱线 3 秒'];return ['山门已开','沿石阶走过山门，即可完成此境'];}
  function refreshUI(){const done=[state.phase>=1,quest.repaired,state.phase>=2,state.won],n=done.filter(Boolean).length;
    const stage=state.won?5:state.phase>=3?4:state.phase>=2?3:quest.repaired?2:state.phase>=1?1:0;
    const titles=['把断开的水槽接起来','水车还缺一枚木销','让雷纹鼓唤醒水车','把水势稳在朱线','亲自走过雨后的桥','这一境，已走通'];
    const copies=['去竹径旁的引水台。转动三段木槽，观察水流是否连通。','水已入渠。到竹径尽头的茶凳找木销，再回河边修好轴座。','鼓旁爻牌自下而上是阳、阴、阴。试着长按一次，短按两次。','去荷塘边转动手轮。水位太低带不动桥，太高会触发保护锁。','桥已经落下。用 WASD 或点地面，穿过山门；不用点击通关按钮。','可以继续漫游庭院，或重新开始。'];
    const hints=['点“一/二/三”走近各水槽，再按 E 旋转。三段长槽都横向相接时，清水会流入河渠。','茶凳在月洞门后。拿到木销，再到河边水车前的轴座按 E 安装。','站到鼓前。按住 E 至少 0.42 秒后松开，再短按 E 两次。错误节奏可以重试。','在荷塘水闸旁 E 加 10%，Q 减 10%。将实际水位稳定在 55%～65%，保持 3 秒。','沿正中木桥走到山门里面，通关会自动出现。','已完成这一境。'];
    $('progress-text').textContent=n+' / 4';done.forEach((d,i)=>$('step-'+i).className=d?'done':i===n?'active':'');$('task-kicker').textContent=state.won?'雨后初晴':'行旅目标 · '+(Math.min(stage,4)+1);$('task-title').textContent=titles[stage];$('task-copy').textContent=copies[stage];$('hint-content').textContent=hints[stage];$('inventory').textContent=quest.repaired?'木销 · 已装入轴座':quest.peg?'木销 × 1':'行囊 · 暂无物品';$('rhythm-readout').textContent=quest.rhythm.map(b=>b==='long'?'长':'短').join(' · ')||'长 · 短 · 短';$('water-readout').textContent=Math.round(quest.pressure)+'%';$('stability').textContent=state.phase>=3?'桥闩已扣稳':state.phase>=2?'稳水 '+quest.stable.toFixed(1)+' / 3 秒':'水轮尚未启动';$('note').textContent=state.phase<2?'坎为水，震为雷。先解开眼前一处，再让变化继续发生。':'雷雨作，解。知进退，也知适度。';
  }
  function beginHold(id){if(blocked())return;const s=stations.find(s=>s.id===id);if(s&&near(s))held={id,start:performance.now()};}
  function endHold(){if(!held)return;const h=held;held=null;act(h.id,{duration:(performance.now()-h.start)/1000});}
  function cancelHold(){held=null;}
  addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||blocked()||e.target?.closest?.('input,textarea,select,[contenteditable="true"]'))return;if(e.code==='KeyE'&&nearest){e.preventDefault();if(nearest.id==='drum')beginHold(nearest.id);else act(nearest.id);}if(e.code==='KeyQ'&&nearest?.id==='valve'){e.preventDefault();act('valve',{delta:-1});}});
  addEventListener('keyup',e=>{if(e.code==='KeyE')endHold();});addEventListener('blur',cancelHold);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelHold();});
  $('interact').addEventListener('pointerdown',e=>{if(!nearest)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);beginHold(nearest.id);});$('interact').addEventListener('pointerup',e=>{e.preventDefault();endHold();});$('interact').addEventListener('pointercancel',cancelHold);$('interact').addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='Enter')&&!e.repeat&&nearest){e.preventDefault();beginHold(nearest.id);}});$('interact').addEventListener('keyup',e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();endHold();}});
  $('decrease').onclick=()=>act('valve',{delta:-1});$('hint').onclick=()=>{state.hints++;$('hint-content').hidden=!$('hint-content').hidden;};
  function bindNavigation(t,c){travel=t;collision=c;const solid=new Set(['stone','darkStone','paleStone','wood','darkWood','roof','bamboo','garden-stone','garden-wood','garden-ink','v4-bark','v4-plaster']);scene.traverse(o=>{if(o.isMesh&&!o.isInstancedMesh&&solid.has(o.material?.name)){let p=o,character=false;while(p){if(p===person)character=true;p=p.parent;}if(!character)occluders.push(o);}});refreshUI();}
  function update(dt,t){clock=t;if(!travel)return;if(blocked())held=null;
    let prefix=true,aligned=true;for(let i=0;i<3;i++){const p=pipes[i];p.rotor.rotation.y+=(p.target-p.rotor.rotation.y)*(1-Math.exp(-dt*12));prefix=prefix&&quest.pipes[i]===0&&Math.abs(p.rotor.rotation.y-p.target)<.05;p.fill.visible=prefix;aligned=aligned&&prefix;}
    if(state.phase===0&&aligned){state.phase=1;state.lower=[0,1,0];chime();toast('三槽相接 · 清流入渠，去修好河边的水车。');$('weather').textContent='清流已至';onChanged();}
    quest.pressure+=(state.flow-quest.pressure)*(1-Math.exp(-dt*2.4));gaugeWater.scale.y=Math.max(1,quest.pressure*.8);gaugeWater.position.y=.13+quest.pressure*.004;handwheel.rotation.z=-state.flow*Math.PI/45;
    if(state.phase===2&&!blocked()){if(quest.pressure>=55&&quest.pressure<=65)quest.stable=Math.min(3,quest.stable+dt);else quest.stable=0;if(quest.stable>=3){state.phase=3;chime();toast('水势平稳 · 桥闩松开，沿木桥走向山门。');$('weather').textContent='雨后初晴';}}
    if(state.phase===3&&state.bridge>.985&&!state.won&&Math.abs(person.position.x)<.55&&person.position.z<-3.62){travel.cancel();onComplete();}
    drumBounce=Math.max(0,drumBounce-dt*4);drumSkin.position.z=.15-drumBounce*.025;beatLights.forEach((o,i)=>o.material.color.set(i<quest.rhythm.length?'#f2c467':'#a5b7a5'));pegRing.rotation.z=t*.8;
    const closest=stations.filter(s=>available(s)&&near(s)).sort((a,b)=>a.point.distanceTo(person.position)-b.point.distanceTo(person.position));nearest=selected&&available(selected)&&near(selected)?selected:closest[0]||null;
    const [title,help]=description(nearest);$('interaction-title').textContent=title;$('interaction-help').textContent=held&&held.id==='drum'?((performance.now()-held.start)/1000>=.42?'重击已蓄力 · 松开敲鼓':'正在蓄力…'):help;$('interact').disabled=!nearest;$('interact').textContent=nearest?.id==='drum'?'按住 / 轻点':'E · 操作';$('decrease').hidden=nearest?.id!=='valve';
    selection.visible=!!nearest;if(nearest)selection.position.set(nearest.point.x,.27,nearest.point.z);
    for(const {s,b} of labels){const show=s.id.startsWith('pipe')?state.phase===0:s.id==='peg'?state.phase>=1&&!quest.peg:s.id==='repair'?state.phase>=1&&!quest.repaired:s.id==='drum'?quest.repaired&&state.phase<2:s.id==='valve'?state.phase===2:state.phase>=3;const compact=innerWidth<=820&&s.id.startsWith('pipe'),anchor=compact?stations[1].point:s.point,p=anchor.clone().add(new THREE.Vector3(0,.16,0)).project(camera);b.hidden=!show||p.z>1;b.style.left=((p.x*.5+.5)*$('canvas-wrap').clientWidth+(compact?(Number(s.id.at(-1))-1)*31:0))+'px';b.style.top=(-p.y*.5+.5)*$('canvas-wrap').clientHeight+'px';b.classList.toggle('near',nearest===s);}
    const ui=[state.phase,quest.peg,quest.repaired,quest.rhythm.length,Math.round(quest.pressure),quest.stable.toFixed(1),state.won].join(':');if(ui!==lastUI){lastUI=ui;refreshUI();}
  }
  function reset(){Object.assign(quest,{pipes:[1,3,1],peg:false,repaired:false,rhythm:[],stable:0,pressure:20,completed:[],events:[]});pipes.forEach((p,i)=>p.target=p.rotor.rotation.y=quest.pipes[i]*Math.PI/2);peg.visible=true;fixedPeg.visible=false;held=selected=nearest=null;drumBounce=0;lastUI='';$('hint-content').hidden=true;refreshUI();}
  return {quest,stations,bindNavigation,update,reset,act,select,approach,near,refreshUI,get nearest(){return nearest?.id||null;},pick(r){return r.intersectObjects(pickables,false).find(h=>available(stations.find(s=>s.id===h.object.userData.stationId)))?.object.userData.stationId||null;}};
}
