import * as THREE from './vendor/three.module.js';
import {inkRenderer,rockGeometry,brushTexture} from './art.js';
import {gardenOutline,extendGarden} from './garden.js';
import {createTravel} from './travel.js';
import {sculptedPine,polishGarden} from './polish.js';
import {createCollision} from './collision.js';
import {createScholar} from './character.js';
import {createAdventure} from './adventure.js';

const $=id=>document.getElementById(id);
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const state={phase:0,lower:[1,0,1],upper:[1,1,0],attempts:0,hints:0,flow:20,started:performance.now(),water:0,bridge:0,gate:0,walking:false,won:false};
let audio=null,muted=true,toastUntil=0,thunderAt=-100;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+4200;}
function tone(freq=440,duration=.16,volume=.07){if(muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function chime(){[330,440,660].forEach((f,i)=>setTimeout(()=>tone(f,.6,.035),i*110));}
function thunder(){thunderAt=clock.getElapsedTime();if(muted)return;try{audio??=new AudioContext();const buffer=audio.createBuffer(1,audio.sampleRate*1.4,audio.sampleRate),a=buffer.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,2);const src=audio.createBufferSource(),filter=audio.createBiquadFilter(),g=audio.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=170;g.gain.value=.17;src.connect(filter).connect(g).connect(audio.destination);src.start();}catch{}}
function mini(bits){return '<div class="mini-gua">'+bits.map(b=>'<div class="'+(b?'solid':'')+'"><i></i><i></i></div>').join('')+'</div>';}
function clue(type){tone(490,.1,.02);if(type==='water'){$('clue-label').textContent='水边石碑';$('clue-title').textContent='外虚，中实';$('clue-text').textContent='“坎中满。” 水的卦象，中间是一根完整的阳爻，上下各是一根断开的阴爻。竹径旁的水槽没有接通，去转动它们，让水流回庭院。';$('clue-diagram').innerHTML=mini([0,1,0])+'<span>坎 · 水<br><small>中间连，上下断</small></span>';}else if(type==='thunder'){$('clue-label').textContent='雷纹石碑';$('clue-title').textContent='一阳，从下而动';$('clue-text').textContent='“震仰盂。” 下面是阳爻，上面两爻都是阴爻。本作把它改编成自下而上的长、短、短三次鼓点。修好轴座后，到雷纹鼓旁试一试。';$('clue-diagram').innerHTML=mini([0,0,1])+'<span>震 · 雷<br><small>下面连，上面断</small></span>';}else{$('clue-label').textContent='山门旧刻';$('clue-title').textContent=state.phase>=3?'山门已开':'路，尚待解';$('clue-text').textContent=state.phase>=3?'水与雷的机关已相继回应。沿木桥走过山门，亲自走完这条归路。':'接水槽、找木销、修水轮、敲雷鼓。最后让水位稳在朱红刻线，木桥才会落下。';$('clue-diagram').innerHTML='';}$('clue').showModal();}
$('water-tag').onclick=()=>clue('water');$('thunder-tag').onclick=()=>clue('thunder');$('gate-tag').onclick=()=>clue('gate');$('about').onclick=()=>$('about-dialog').showModal();document.querySelectorAll('dialog').forEach(d=>{d.querySelectorAll('.close,.close-action').forEach(b=>b.onclick=()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
$('sound').onclick=()=>{muted=!muted;$('sound').textContent='声音 '+(muted?'关':'开');$('sound').setAttribute('aria-pressed',String(!muted));tone(520,.3);};

// All scene elements are authored geometry. No external image, font or network dependency.
const scene=new THREE.Scene();scene.background=new THREE.Color('#dce5df');scene.fog=new THREE.Fog('#dce5df',32,67);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;$('canvas-wrap').append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(36,1,.1,110);const focus=new THREE.Vector3(0,.55,1.7);let yaw=.48,pitch=.76,radius=27,targetYaw=yaw,targetPitch=pitch,targetRadius=radius;
const hemi=new THREE.HemisphereLight('#e3edf4','#546f77',1.45);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff0d1',2.3);sun.position.set(-7,13,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:1,far:35});sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;sun.shadow.radius=3;scene.add(sun);const fill=new THREE.DirectionalLight('#bed8e3',.45);fill.position.set(9,5,-5);scene.add(fill);const flash=new THREE.PointLight('#cce7ed',0,25);flash.position.set(0,8,0);scene.add(flash);
const ramp=new THREE.DataTexture(new Uint8Array([105,165,215,250]),4,1,THREE.RedFormat);ramp.minFilter=ramp.magFilter=THREE.NearestFilter;ramp.needsUpdate=true;
const mats={};function mat(name,color){if(!mats[name]){mats[name]=new THREE.MeshToonMaterial({color,gradientMap:ramp});mats[name].name=name;}return mats[name];}
const stone=mat('stone','#93a4a3'),darkStone=mat('darkStone','#4c666c'),paleStone=mat('paleStone','#dfddc9'),earth=mat('earth','#596e72'),soil=mat('soil','#a8b596'),wood=mat('wood','#a27647'),darkWood=mat('darkWood','#4f524b'),red=mat('red','#bd533f'),roofMat=mat('roof','#456772'),gold=mat('gold','#d5b675'),leaf=mat('leaf','#255f56'),leafLight=mat('leafLight','#4b8870'),waterMat=new THREE.MeshToonMaterial({color:'#46b8ba',gradientMap:ramp,transparent:true,opacity:.92});
stone.map=brushTexture('stone');paleStone.map=stone.map;wood.map=brushTexture('wood');darkWood.map=wood.map;roofMat.map=brushTexture('stone');
// Illustration palette: cooler blue shadows, warm paper lights, restrained vermilion accents.
soil.color.set('#b2c5a0');roofMat.color.set('#497c8b');wood.color.set('#b68a55');paleStone.color.set('#ede4c9');darkStone.color.set('#577680');
renderer.setPixelRatio(Math.min(Math.max(devicePixelRatio,1.75),2));
function mesh(geometry,material,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,material,x,y,z,parent=scene){return mesh(new THREE.BoxGeometry(w,h,d),material,x,y,z,parent);}
function cylinder(r1,r2,h,material,x,y,z,parent=scene,n=12){return mesh(new THREE.CylinderGeometry(r1,r2,h,n),material,x,y,z,parent);}
function beam(a,b,r,material,parent=scene){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),v=bv.clone().sub(av);const m=cylinder(r,r,v.length(),material,...av.clone().add(bv).multiplyScalar(.5).toArray(),parent,8);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return m;}
let seed=719;function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const ground=cylinder(50,50,.12,mat('ground','#d1ddd5'),0,-1.45,0,scene,80);ground.castShadow=false;
// An irregular stone island, layered like a scholar's miniature landscape.
const shape=new THREE.Shape();const outline=gardenOutline;outline.forEach(([x,z],i)=>i?shape.lineTo(x,z):shape.moveTo(x,z));shape.closePath();const base=mesh(new THREE.ExtrudeGeometry(shape,{depth:.72,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.16,bevelThickness:.2}),earth);base.rotation.x=Math.PI/2;base.position.y=-.32;
for(let i=0;i<30;i++){const a=i/30*Math.PI*2,r=5.2+rng()*.3;const rock=mesh(rockGeometry(.5+rng()*.3,.4+rng()*.22,.45,rng()*5),i%2?darkStone:stone,Math.cos(a)*r,-.43,Math.sin(a)*r*.76);rock.rotation.y=rng()*6;}
// Two banks and a cut channel, with a bridge that physically connects them.
function bank(bound,south){const polygon=outline.map(([x,z])=>[x*.97,z*.97]),points=[];for(let i=0;i<polygon.length;i++){const a=polygon[i],b=polygon[(i+1)%polygon.length],insideA=south?a[1]>=bound:a[1]<=bound,insideB=south?b[1]>=bound:b[1]<=bound;if(insideA)points.push(a);if(insideA!==insideB){const t=(bound-a[1])/(b[1]-a[1]);points.push([a[0]+(b[0]-a[0])*t,bound]);}}const s=new THREE.Shape();points.forEach(([x,z],i)=>i?s.lineTo(x,z):s.moveTo(x,z));s.closePath();const m=mesh(new THREE.ExtrudeGeometry(s,{depth:.34,bevelEnabled:false}),soil);m.rotation.x=Math.PI/2;m.position.y=.24;}
bank(1.01,true);bank(-.96,false);
box(11.4,.08,1.8,darkStone,0,.04,.04);const stream=box(11.35,.045,1.56,waterMat,0,.19,.04);stream.visible=false;
const waterfall=box(.055,1.48,1.35,new THREE.MeshStandardMaterial({color:'#75bdb0',transparent:true,opacity:.7,roughness:.28}),5.72,-.55,.04);waterfall.visible=false;waterfall.castShadow=false;
for(const z of [-.91,.97])for(let x=-5;x<=5;x+=.48){const b=box(.45,.25,.25,x%2?stone:paleStone,x,.3,z);b.rotation.y=(rng()-.5)*.09;}
// Retaining walls and paved approach.
for(let i=0;i<8;i++){const z=1.45+i*.39;box(1.38,.08,.32,paleStone,0,.285,z);if(i<6)box(1.34,.07,.35,paleStone,0,.29,-1.42-i*.4);}
for(let i=0;i<42;i++){const x=(rng()-.5)*9.7,z=(rng()-.5)*7.5;if(Math.abs(z)<1.2||Math.abs(x)<1.1)continue;const r=mesh(rockGeometry(.1+rng()*.18,.07,.12,rng()),stone,x,.28,z);r.rotation.y=rng()*6;}
// Mountain forms behind the courtyard.
function rock(x,z,s,height){const g=new THREE.Group();g.position.set(x,.1,z);scene.add(g);for(let j=0;j<3;j++){const h=height*(1-j*.21),offset=(j-1)*s*.48;const m=mesh(rockGeometry(s*(.65-j*.06),h*.52,s*.57,j*1.9+x),j===1?stone:darkStone,offset,h*.47,j*.15,g);m.rotation.z=(j-1)*.09;const moss=mesh(rockGeometry(s*.34,.12,s*.36,j),leafLight,offset,h*.91+.03,j*.15,g);}return g;}
rock(-3.8,-3.55,.92,2.7);rock(-4.75,-2.9,.7,1.8);rock(3.8,-3.65,.94,3.15);rock(4.65,-2.9,.7,2.2);rock(2.7,-4.25,.6,1.8);
for(let i=0;i<17;i++){const a=rng()*6.28,x=Math.cos(a)*(4.3+rng()*.5),z=Math.sin(a)*(3.4+rng()*.4);if((z>-.5&&z<1.2)||Math.abs(x)<1.05)continue;const r=mesh(rockGeometry(.35+rng()*.25,.22+rng()*.3,.34,rng()*5),i%2?stone:paleStone,x,.4,z);r.rotation.y=rng()*6;}
// Pine silhouettes: visible branching, layered horizontal needle canopies.
function pine(x,z,h,lean=0){for(let i=0;i<1680;i++)rng();return sculptedPine(x,z,h,lean,{scene,mat});}
pine(-4.35,2.6,2.5,-.33);pine(4,2.55,2.65,.3);pine(4.6,1.7,1.4,-.15);pine(-2.5,-3.6,2.1,.22);pine(2.55,-3.1,1.8,-.18);
// Grass tufts around stone edges.
for(let i=0;i<65;i++){const x=(rng()-.5)*10,z=(rng()-.5)*7.8;if(Math.abs(z)<1.2||Math.abs(x)<1)continue;for(let j=0;j<3;j++){const m=mesh(new THREE.ConeGeometry(.035,.18+rng()*.15,3),leaf,x+j*.065,.34,z);m.rotation.z=(rng()-.5)*.5;}}
function roof(w,d,y,parent){const nx=30,nz=20,positions=[],uvs=[],indices=[];const height=(x,z)=>y+.57*Math.pow(1-Math.abs(z)/(d*.5),1.8)+.21*Math.pow(Math.abs(x)/(w*.5),7)+.05*Math.pow(Math.abs(z)/(d*.5),8);for(let j=0;j<=nz;j++)for(let i=0;i<=nx;i++){const x=(i/nx-.5)*w,z=(j/nz-.5)*d;positions.push(x,height(x,z),z);uvs.push(i/nx,j/nz);}for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const a=j*(nx+1)+i;indices.push(a,a+nx+1,a+1,a+1,a+nx+1,a+nx+2);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geo.setIndex(indices);geo.computeVertexNormals();const rm=roofMat.clone();rm.side=THREE.DoubleSide;mesh(geo,rm,0,0,0,parent);
  // Each curved tile course follows the roof surface, including raised eaves.
  const tileMat=mat('tile-edge','#71939a');for(let i=0;i<=Math.round(w/.15);i++){const x=-w/2+i*w/Math.round(w/.15);for(const side of [-1,1]){const points=[];for(let j=0;j<=12;j++){const z=side*j/12*d*.5;points.push(new THREE.Vector3(x,height(x,z)+.015,z));}mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),12,.018,5,false),tileMat,0,0,0,parent);}}
  for(const side of [-1,1]){const points=[];for(let i=0;i<=18;i++){const x=(i/18-.5)*w;points.push(new THREE.Vector3(x,height(x,side*d/2),side*d/2));}mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),24,.055,8,false),darkWood,0,0,0,parent);}
  const ridge=new THREE.CatmullRomCurve3([new THREE.Vector3(-w*.53,y+.82,0),new THREE.Vector3(-w*.4,y+.6,0),new THREE.Vector3(0,y+.58,0),new THREE.Vector3(w*.4,y+.6,0),new THREE.Vector3(w*.53,y+.82,0)]);mesh(new THREE.TubeGeometry(ridge,25,.06,8,false),roofMat,0,0,0,parent);
  for(const x of [-w*.45,w*.45]){for(const side of [-1,1]){const a=[x,y-.07,side*d*.32],b=[x*.75,y-.2,side*d*.32];beam(a,b,.055,wood,parent);}}
}
// Rain pavilion, open on all sides.
const pavilion=new THREE.Group();pavilion.position.set(-3.15,.25,-1.8);scene.add(pavilion);box(2,.18,1.75,paleStone,0,.06,0,pavilion);for(const x of [-.72,.72])for(const z of [-.6,.6]){cylinder(.07,.08,1.5,wood,x,.86,z,pavilion);box(.22,.13,.22,stone,x,.2,z,pavilion);}roof(2.2,1.85,1.75,pavilion);box(1.7,.1,.24,wood,0,.61,-.59,pavilion);box(.12,.5,.12,wood,-.68,.36,-.59,pavilion);box(.12,.5,.12,wood,.68,.36,-.59,pavilion);
// Gate wall, tiles, stone frame and two doors that swing on hinges.
const gateGroup=new THREE.Group();gateGroup.position.set(0,.24,-3.28);scene.add(gateGroup);for(const x of [-1.28,1.28]){box(.55,2.05,.62,stone,x,1.03,0,gateGroup);box(.66,.18,.75,paleStone,x,.13,0,gateGroup);box(1.3,.93,.32,stone,x*1.55,.47,.03,gateGroup);}box(2.9,.34,.64,paleStone,0,2.12,0,gateGroup);roof(3.35,.95,2.39,gateGroup);
const doorLeft=new THREE.Group(),doorRight=new THREE.Group();doorLeft.position.set(-1,.12,.12);doorRight.position.set(1,.12,.12);gateGroup.add(doorLeft,doorRight);for(const [g,s] of [[doorLeft,1],[doorRight,-1]]){box(.99,1.87,.14,darkWood,s*.49,.94,0,g);for(let i=0;i<5;i++)box(.13,1.66,.055,wood,s*(.12+i*.18),.94,.085,g);for(const y of [.32,1.5])box(.9,.065,.065,gold,s*.49,y,.13,g);const ring=mesh(new THREE.TorusGeometry(.09,.017,6,18),gold,s*.82,.91,.16,g);}
const plaque=box(.83,.27,.06,darkWood,0,2.13,.355,gateGroup);
function textSprite(text,size=.5,color='#f0e4b6'){const c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font='62px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,128,66);const t=new THREE.CanvasTexture(c),m=new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false});const sp=new THREE.Sprite(m);sp.scale.set(size*2,size,1);return sp;}
const inscription=textSprite('解',.24);inscription.position.set(0,2.13,.399);gateGroup.add(inscription);
// Stone lanterns along the path.
function lantern(x,z){cylinder(.18,.23,.14,paleStone,x,.31,z);box(.15,.42,.15,stone,x,.58,z);box(.38,.08,.38,paleStone,x,.81,z);const glow=new THREE.MeshStandardMaterial({color:'#efd49a',emissive:'#d6a654',emissiveIntensity:.25});box(.25,.28,.25,glow,x,.98,z);for(const dx of [-.14,.14])for(const dz of [-.14,.14])box(.035,.34,.035,darkStone,x+dx,.98,z+dz);const cap=mesh(new THREE.ConeGeometry(.36,.23,4),roofMat,x,1.23,z);cap.rotation.y=Math.PI/4;}
lantern(-1.15,2.65);lantern(1.15,2.65);lantern(-1.45,-2);lantern(1.45,-2);
// Wooden drawbridge: hinge is on the south bank.
const bridge=new THREE.Group();bridge.position.set(0,.36,1.02);scene.add(bridge);for(let i=0;i<11;i++)box(1.48,.1,.185,i%2?wood:darkWood,0,0,-.1-i*.185,bridge);for(const x of [-.62,.62]){box(.11,.17,2.15,darkWood,x,-.07,-.99,bridge);for(const z of [-.15,-.95,-1.82])box(.065,.53,.065,wood,x,.27,z,bridge);box(.075,.075,2.03,wood,x,.53,-.99,bridge);}bridge.rotation.x=1.05;
// Water wheel and pressure marker on the east bank.
const wheel=new THREE.Group();wheel.position.set(3.45,.92,.05);scene.add(wheel);for(const depth of [-.17,.17]){const rim=mesh(new THREE.TorusGeometry(.69,.055,8,36),wood,0,0,depth,wheel);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;beam([0,0,depth],[Math.cos(a)*.69,Math.sin(a)*.69,depth],.029,wood,wheel);}}for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const paddle=box(.21,.07,.51,wood,Math.cos(a)*.68,Math.sin(a)*.68,0,wheel);paddle.rotation.z=a;}const axle=cylinder(.07,.07,.9,darkStone,3.45,.92,.05);axle.rotation.x=Math.PI/2;beam([3.45,.24,.55],[3.45,.94,.55],.08,wood);beam([3.45,.24,-.47],[3.45,.94,-.47],.08,wood);
box(.3,1.15,.25,paleStone,4.55,.8,-1.17);box(.34,.045,.3,red,4.55,1.06,-1.17);const waterMeter=box(.075,.15,.3,waterMat,4.55,.32,-1.01);
// Puzzle altar and two clue stones.
const altar=new THREE.Group();altar.position.set(-2.3,.27,2.1);scene.add(altar);cylinder(.62,.73,.18,darkStone,0,.09,0,altar,8);cylinder(.49,.54,.64,stone,0,.47,0,altar,8);cylinder(.59,.59,.09,paleStone,0,.83,0,altar,8);const symbolGroup=new THREE.Group();symbolGroup.position.set(0,.9,0);symbolGroup.rotation.x=-Math.PI/2;altar.add(symbolGroup);
function updateSymbol(){if(typeof symbolGroup==='undefined')return;while(symbolGroup.children.length){const m=symbolGroup.children[0];symbolGroup.remove(m);m.geometry.dispose();}const arr=[...state.upper,...state.lower];arr.forEach((v,i)=>{const y=.28-i*.11;const material=i<3?(state.phase>=2?gold:darkStone):(state.phase>=1?gold:darkStone);if(v)box(.55,.043,.026,material,0,y,0,symbolGroup);else{box(.215,.043,.026,material,-.167,y,0,symbolGroup);box(.215,.043,.026,material,.167,y,0,symbolGroup);}});}
const pickables=[];function clueStone(x,z,type,bits){const g=new THREE.Group();g.position.set(x,.25,z);scene.add(g);const m=box(.57,.95,.28,darkStone,0,.5,0,g);m.userData.clue=type;pickables.push(m);box(.7,.12,.43,stone,0,.08,0,g);bits.forEach((v,i)=>{if(v)box(.34,.045,.026,paleStone,0,.78-i*.15,.154,g);else for(const s of [-1,1])box(.135,.045,.026,paleStone,s*.105,.78-i*.15,.154,g);});return g;}
clueStone(-3.9,1.45,'water',[0,1,0]);clueStone(2.12,-1.65,'thunder',[0,0,1]);
// Scholar: short jade robe, articulated limbs and world-space planted feet.
const scholar=createScholar({scene,mat}),{person,legs,hat}=scholar;
// Architectural joinery, lattice screens, masonry seams and quiet garden planting.
for(const side of [-1,1]){box(.055,1.38,.055,gold,side*.99,1.16,.27,gateGroup);for(let y=.36;y<1.9;y+=.31){box(.54,.012,.008,darkStone,side*1.28,y,.316,gateGroup);const crack=box(.012,.3,.009,darkStone,side*1.28+((Math.floor(y*10)%2)?-.1:.1),y+.15,.317,gateGroup);}box(.1,.2,.16,wood,side*.72,1.62,-.6,pavilion);}
for(const side of [-1,1])for(let j=0;j<5;j++){const z=-.52+j*.26;beam([side*.74,.64,z],[side*.74,1.25,z],.016,darkWood,pavilion);}for(let i=0;i<7;i++)box(.012,.012,1.48,wood,-.65+i*.216,.2,0,pavilion);
for(let i=0;i<12;i++){const x=-4.3+rng()*8.6,z=(i%2?1:-1)*(1.3+rng()*2.3);if(Math.abs(x)<1.45)continue;const patch=mesh(new THREE.CircleGeometry(.2+rng()*.23,16),mat('moss','#6e936d'),x,.247,z);patch.rotation.x=-Math.PI/2;patch.scale.y=.65;}
// Autumn accent: delicate branching and clustered individual leaves.
const maple=new THREE.Group();maple.position.set(-3.15,.24,3.25);scene.add(maple);beam([0,0,0],[.1,1.55,0],.045,darkWood,maple);const leafGeo=new THREE.SphereGeometry(.075,5,3),mapleLeaves=new THREE.InstancedMesh(leafGeo,mat('maple','#c27c49'),180);maple.add(mapleLeaves);mapleLeaves.castShadow=true;const ml=new THREE.Object3D();let mi=0;for(let j=0;j<6;j++){const a=j*2.4,r=.4+rng()*.25,ex=Math.cos(a)*r,ez=Math.sin(a)*r,y=1.15+rng()*.55;beam([.06,y*.7,0],[ex,y,ez],.02,darkWood,maple);for(let k=0;k<30;k++){ml.position.set(ex+(rng()-.5)*.6,y+(rng()-.5)*.23,ez+(rng()-.5)*.5);ml.rotation.set(rng(),rng()*6,rng());ml.scale.set(1+rng(),.35,1+rng());ml.updateMatrix();mapleLeaves.setMatrixAt(mi,ml.matrix);mapleLeaves.setColorAt(mi,new THREE.Color(k%3===0?'#e0a76b':k%3===1?'#b85e3b':'#d58548'));mi++;}}
// Small ivory flowers gather beside stones, keeping the central route visually quiet.
const flowers=new THREE.InstancedMesh(new THREE.SphereGeometry(.033,6,4),mat('flower','#fff1c5'),180);scene.add(flowers);flowers.castShadow=false;const flowerDummy=new THREE.Object3D();let flowerCount=0;
for(const [cx,cz] of [[-1.75,3.6],[2.3,3.3],[-4.4,-1.55],[3.4,-2.7]]){for(let j=0;j<9;j++){const x=cx+(rng()-.5)*.65,z=cz+(rng()-.5)*.5,y=.36+rng()*.13;beam([x,.24,z],[x,y,z],.008,leaf);for(let k=0;k<5;k++){const a=k*Math.PI*2/5;flowerDummy.position.set(x+Math.cos(a)*.035,y,z+Math.sin(a)*.035);flowerDummy.scale.set(1,.4,1);flowerDummy.updateMatrix();flowers.setMatrixAt(flowerCount++,flowerDummy.matrix);}}}flowers.count=flowerCount;
// A small rain pool and ripple rings, activated by the first mechanism.
const ripples=[];for(let i=0;i<19;i++){const ring=mesh(new THREE.RingGeometry(.12,.132,28),new THREE.MeshBasicMaterial({color:'#b2e0c8',transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false}),-4.9+rng()*9.8,.22,-.63+rng()*1.25);ring.rotation.x=-Math.PI/2;ring.userData.offset=rng()*4;ripples.push(ring);}
const foam=[];for(let i=0;i<30;i++){const f=box(.08+rng()*.18,.009,.018,new THREE.MeshBasicMaterial({color:'#c2e4c9',transparent:true,opacity:.55}),-5+rng()*10,.225,-.62+rng()*1.2);f.userData.speed=.25+rng()*.3;foam.push(f);}
const rainCount=170,positions=new Float32Array(rainCount*3);for(let i=0;i<rainCount;i++){positions[i*3]=(rng()-.5)*14;positions[i*3+1]=rng()*8;positions[i*3+2]=(rng()-.5)*12;}const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(positions,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:'#d7eee1',size:.035,transparent:true,opacity:0,depthWrite:false}));scene.add(rain);
const garden=extendGarden({scene,mesh,box,cylinder,beam,mat,rockGeometry,rng,lantern,pine,roof});
const refined=polishGarden({scene,gateGroup,pavilion,stone,paleStone,wood,darkWood,roofMat,mat,box,cylinder,beam,waterMat,stream,waterfall,reduce});
const adventure=createAdventure({scene,camera,person,scholar,state,mat,mesh,box,cylinder,beam,toast,tone,chime,thunder,onComplete:finishJourney,onChanged:updateSymbol});
const collision=createCollision({scene,person,bridge,doorLeft,doorRight,outline,state,wheel});
const travel=createTravel({scene,camera,person,legs,hat,rig:scholar,state,collision,toast,reduce,onComplete:finishJourney});
adventure.bindNavigation(travel,collision);
function finishJourney(){if(state.won)return;state.won=true;const secs=Math.floor((performance.now()-state.started)/1000);$('win-time').textContent=Math.floor(secs/60)+':'+String(secs%60).padStart(2,'0');$('win-attempts').textContent=state.attempts;$('win').showModal();adventure.refreshUI();chime();}
$('mouse-follow').onclick=()=>{const active=travel.toggle();$('mouse-follow').setAttribute('aria-pressed',String(active));toast(active?'随鼠标走已开启。鼠标移到空地，旅人会跟上。':'随鼠标走已关闭。点击地面仍可行走，拖动可环看。');};
// Camera controls with restrained orbit, pinch zoom, and click raycasts.
const pointers=new Map();let dragDistance=0,lastDown=null,pinchDist=0,downAt=0;const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','庭院：WASD 行走，E 操作机关，Q 关小水闸，拖动环看');
canvas.addEventListener('pointerdown',()=>canvas.focus({preventScroll:true}));
canvas.addEventListener('pointerdown',e=>{downAt=performance.now();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});dragDistance=0;lastDown={x:e.clientX,y:e.clientY};if(pointers.size===2){const a=[...pointers.values()];pinchDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);}});
canvas.addEventListener('pointermove',e=>{const prev=pointers.get(e.pointerId);if(!prev)return;const dx=e.clientX-prev.x,dy=e.clientY-prev.y;dragDistance+=Math.abs(dx)+Math.abs(dy);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);targetRadius=THREE.MathUtils.clamp(targetRadius+(pinchDist-dist)*.045,13,28);pinchDist=dist;}else{targetYaw-=dx*.005;targetPitch=THREE.MathUtils.clamp(targetPitch+dy*.003,.38,1.4);}});
function groundPoint(e){const rect=canvas.getBoundingClientRect(),point=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(point,camera);return {ray,point:ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-.31),new THREE.Vector3())};}
canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(dragDistance<7&&lastDown&&e.button===0){const {ray,point}=groundPoint(e),station=adventure.pick(ray),hit=ray.intersectObjects(pickables)[0];if(station)adventure.select(station,{duration:(performance.now()-downAt)/1000});else if(hit)clue(hit.object.userData.clue);else if(point)travel.command(point.x,point.z);}});canvas.addEventListener('pointercancel',e=>pointers.delete(e.pointerId));canvas.addEventListener('wheel',e=>{e.preventDefault();targetRadius=THREE.MathUtils.clamp(targetRadius+e.deltaY*.01,13,36);},{passive:false});
let lastFollow=0;canvas.addEventListener('pointermove',e=>{if(pointers.size||e.pointerType==='touch'||state.walking)return;const {point}=groundPoint(e);if(!point)return;const valid=travel.canWalk(point.x,point.z);travel.hover.visible=valid;travel.hover.position.set(point.x,collision.heightAt(point.x,point.z)+.025,point.z);canvas.style.cursor=valid?'crosshair':'default';if(travel.following&&valid&&performance.now()-lastFollow>220){travel.command(point.x,point.z,{silent:true});lastFollow=performance.now();}});canvas.addEventListener('pointerleave',()=>travel.hover.visible=false);
$('view-home').onclick=()=>{targetYaw=.48;targetPitch=.76;targetRadius=innerWidth<=820?33:27;};$('view-top').onclick=()=>{targetYaw=0;targetPitch=1.35;targetRadius=27;};
const tagPositions=[['water-tag',new THREE.Vector3(-3.9,1.52,1.45)],['thunder-tag',new THREE.Vector3(2.12,1.52,-1.65)],['gate-tag',new THREE.Vector3(0,3.5,-3.28)]];
function resize(){const r=$('world').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.fov=innerWidth<=820?43:36;focus.y=innerWidth<=820?1.35:.55;camera.updateProjectionMatrix();}addEventListener('resize',resize);if(innerWidth<=820)radius=targetRadius=33;resize();
const clock=new THREE.Clock();let last=0;const drawInk=inkRenderer(renderer,scene,camera);
function frame(){requestAnimationFrame(frame);const t=clock.getElapsedTime(),dt=Math.min(t-last,.05);last=t;const ease=reduce?1:1-Math.exp(-dt*4);yaw+=(targetYaw-yaw)*ease;pitch+=(targetPitch-pitch)*ease;radius+=(targetRadius-radius)*ease;camera.position.set(Math.sin(yaw)*Math.cos(pitch)*radius,Math.sin(pitch)*radius,Math.cos(yaw)*Math.cos(pitch)*radius).add(focus);camera.lookAt(focus);
  state.water+=((state.phase>0?1:0)-state.water)*(reduce?1:dt*1.4);stream.visible=state.water>.01;stream.scale.x=Math.max(.001,state.water);stream.position.x=-5.675*(1-state.water);waterMat.opacity=.72+state.water*.14;waterfall.visible=state.water>.95;
  state.bridge+=((state.phase>=3?1:0)-state.bridge)*(reduce?1:dt*1.6);bridge.rotation.x=1.05*(1-state.bridge);state.gate+=((state.phase>=3?1:0)-state.gate)*(reduce?1:dt*.85);doorLeft.rotation.y=-state.gate*1.5;doorRight.rotation.y=state.gate*1.5;
  if(state.phase>=2&&!reduce)wheel.rotation.z-=dt*(.3+state.flow*.011);waterMeter.scale.y=1+(state.phase>=2?state.flow/100:0)*5;waterMeter.position.y=.32+(waterMeter.scale.y-1)*.075;
  for(const r of ripples){r.visible=state.phase>0;if(!reduce){const cycle=(t*.38+r.userData.offset)%1;r.scale.setScalar(.4+cycle*2);r.material.opacity=(1-cycle)*.2;}}
  for(const f of foam){f.visible=state.phase>0;if(!reduce){f.position.x+=dt*f.userData.speed;if(f.position.x>5.05)f.position.x=-5.05;}}
  const elapsed=t-thunderAt;flash.intensity=elapsed>=0&&elapsed<.45&&!reduce?Math.max(0,Math.sin(elapsed*35))*15:0;rain.material.opacity=state.phase===2&&!reduce?.35:0;if(state.phase===2&&!reduce){for(let i=0;i<rainCount;i++){positions[i*3+1]-=dt*6;if(positions[i*3+1]<.4)positions[i*3+1]=8;}rainGeo.attributes.position.needsUpdate=true;}
  travel.update(dt,t);adventure.update(dt,t);garden.update(t,reduce);refined.update(t);
  for(const [id,point] of tagPositions){const p=point.clone().project(camera);const el=$(id);el.style.left=(p.x*.5+.5)*canvas.clientWidth+'px';el.style.top=(-p.y*.5+.5)*canvas.clientHeight+'px';el.style.visibility=p.z>1?'hidden':'visible';}
  if(performance.now()>toastUntil)$('toast').classList.remove('show');drawInk();
}
function reset(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());Object.assign(state,{phase:0,lower:[1,0,1],upper:[1,1,0],attempts:0,hints:0,flow:20,started:performance.now(),water:0,bridge:0,gate:0,walking:false,won:false});thunderAt=-100;person.position.set(0,.31,3.25);travel.reset();adventure.reset();$('weather').textContent='山雨未至';$('view-home').click();updateSymbol();toast('庭院归于静候。再读一次山水。');}
$('reset').onclick=reset;$('replay').onclick=reset;$('explore').onclick=()=>$('win').close();updateSymbol();frame();$('loading').hidden=true;window.__game={state,renderer,camera,person,scholar,travel,collision,adventure,outline,reset};window.__READY=true;
