const {chromium}=require('C:/Users/宋/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),{pathToFileURL}=require('node:url');
const out='E:/video-outputs/yijing-rain-garden';
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
try{await page.route(/^https?:/,r=>r.abort());await page.goto(pathToFileURL(out+'/易境-雨后通途.html').href);await page.waitForFunction(()=>window.__READY);await page.waitForTimeout(700);
const at=async(x,z)=>page.evaluate(({x,z})=>{const p=__game.person.position.clone().set(x,.31,z).project(__game.camera),r=__game.renderer.domElement.getBoundingClientRect();return{x:r.left+(p.x*.5+.5)*r.width,y:r.top+(-p.y*.5+.5)*r.height};},{x,z});
const click=async(x,z)=>{const p=await at(x,z);await page.mouse.click(p.x,p.y);};
await click(1.9,6.6);await page.waitForFunction(()=>__game.travel.moving);await page.waitForTimeout(400);const moving=await page.evaluate(()=>({x:__game.person.position.x,z:__game.person.position.z,yaw:__game.person.rotation.y,leg:__game.person.children.filter(o=>o.geometry?.type==='BoxGeometry').map(o=>o.rotation.x)}));assert(moving.z>3.25);assert(Math.abs(moving.yaw)>.1);await page.waitForFunction(()=>!__game.travel.moving);assert(await page.evaluate(()=>__game.person.position.z>6));await page.screenshot({path:out+'/08-expanded-garden.png'});
// The old north bank is unreachable until the bridge physically lowers.
const before=await page.evaluate(()=>__game.person.position.toArray());await click(0,-1.6);await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>__game.travel.moving),false);const after=await page.evaluate(()=>__game.person.position.toArray());assert(Math.abs(before[0]-after[0])<.01&&Math.abs(before[2]-after[2])<.01);
// Pond and world edge cannot be destinations.
assert.equal(await page.evaluate(()=>__game.travel.command(4.1,5.4,{silent:true})),false);assert.equal(await page.evaluate(()=>__game.travel.command(20,20,{silent:true})),false);
await page.locator('#mouse-follow').click();assert.equal(await page.locator('#mouse-follow').getAttribute('aria-pressed'),'true');const follow=await at(-.6,7.8);await page.mouse.move(follow.x,follow.y,{steps:8});await page.waitForFunction(()=>__game.travel.moving);await page.waitForFunction(()=>!__game.travel.moving);assert(await page.evaluate(()=>__game.person.position.z>7));await page.locator('#mouse-follow').click();
// Solve all original mechanisms after free roaming, then walk back from the enlarged map.
for(const i of [0,1,2])await page.locator('#lower-lines button').nth(i).click();await page.locator('#submit').click();for(const i of [0,1,2])await page.locator('#upper-lines button').nth(i).click();await page.locator('#submit').click();await page.locator('#flow').fill('60');await page.locator('#submit').click();await page.waitForFunction(()=>__game.state.bridge>.95);await page.locator('#submit').click();await page.waitForFunction(()=>__game.state.won,{},{timeout:20000});assert(await page.locator('#win').isVisible());await page.locator('#explore').click();
await click(1.9,6.6);await page.waitForFunction(()=>__game.travel.moving);await page.waitForFunction(()=>!__game.travel.moving,{},{timeout:20000});assert(await page.evaluate(()=>__game.person.position.z>6));await page.screenshot({path:out+'/09-garden-open.png'});
await page.locator('#reset').click();assert.equal(await page.evaluate(()=>__game.travel.moving),false);assert.equal(await page.evaluate(()=>__game.travel.following),false);assert.equal(await page.evaluate(()=>__game.state.phase),0);
const area=await page.evaluate(()=>{const area=a=>Math.abs(a.reduce((s,p,i)=>{const q=a[(i+1)%a.length];return s+p[0]*q[1]-q[0]*p[1]},0))/2;return area(__game.outline);});assert(area>130);
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1400);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:out+'/10-expanded-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);const report={passed:true,errors,area,checks:['actual canvas click movement','smooth turning','expanded area reachable','closed bridge blocks crossing','pond and edge blocked','pointer-follow toggle and movement','complete original puzzle after exploring','return from north bank after completion','reset cancels paths and follow','mobile no overflow'],time:new Date().toISOString()};fs.writeFileSync(out+'/qa-travel-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
